import { FaJava, FaCode, FaServer, FaTerminal } from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiRust,
  SiPhp,
  SiGnubash,
  SiDocker,
  SiPostgresql,
  SiMysql,
  SiMariadb,
  SiFastapi,
  SiHtml5,
  SiCss3,
  SiPandas,
  SiScikitlearn,
  SiJupyter,
  SiKaggle,
  SiStreamlit,
  SiCloudflare,
  SiCanva,
  SiAseprite,
  SiApachemaven,
  SiSpringboot,
  SiLinux,
  SiReact,
} from "react-icons/si";

// Every icon below was verified to exist in react-icons@4.7.1 (pinned in yarn.lock)
const TECH_ICONS = {
  Java: FaJava,
  "Spring Boot": SiSpringboot,
  Maven: SiApachemaven,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  Rust: SiRust,
  PHP: SiPhp,
  Bash: SiGnubash,
  Nushell: FaTerminal,
  Docker: SiDocker,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MariaDB: SiMariadb,
  FastAPI: SiFastapi,
  HTML5: SiHtml5,
  CSS3: SiCss3,
  React: SiReact,
  Pandas: SiPandas,
  "scikit-learn": SiScikitlearn,
  Jupyter: SiJupyter,
  Kaggle: SiKaggle,
  Streamlit: SiStreamlit,
  Cloudflare: SiCloudflare,
  Linux: SiLinux,
  Caddy: FaServer,
  Canva: SiCanva,
  Aseprite: SiAseprite,
};

export const getTechIcon = (name) => TECH_ICONS[name] || FaCode;

export const TECH_CATEGORY_ORDER = [
  "Backend",
  "Frontend & UI",
  "Databases",
  "DevOps & Automation",
  "Data & ML",
];
